apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloakdb
  KC_HOSTNAME: mycluster.local.com
  KC_HTTP_RELATIVE_PATH: /keycloak
  KC_PROXY_HEADERS: xforwarded
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
